CREATE TABLE IF NOT EXISTS account_notification (
    notification_pk BIGINT NOT NULL AUTO_INCREMENT,
    notification_id VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL,
    type VARCHAR(80) NOT NULL,
    category VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    title_key VARCHAR(120) NOT NULL,
    body_key VARCHAR(120) NOT NULL,
    params_json TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    action_type VARCHAR(32) NULL,
    action_label_key VARCHAR(120) NULL,
    action_payload_json TEXT NULL,
    dedupe_key VARCHAR(120) NULL,
    occurred_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_account_notification PRIMARY KEY (notification_pk),
    CONSTRAINT uk_account_notification_id UNIQUE (notification_id),
    CONSTRAINT uk_account_notification_dedupe_key UNIQUE (dedupe_key),
    CONSTRAINT fk_account_notification_account FOREIGN KEY (account_id) REFERENCES account_master (account_id),
    INDEX idx_account_notification_account_status_occurred (account_id, status, occurred_at DESC),
    INDEX idx_account_notification_account_occurred (account_id, occurred_at DESC)
);
