spring.config.activate.on-profile=prod

# Production profile
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.cookie.same-site=Lax
jwt.cookie.http-only=true
jwt.cookie.secure=true
jwt.issuer=terra-api
jwt.audience-api=terra-api
jwt.audience-realtime=terra-realtime
jwt.allowed-algorithms[0]=HS512
jwt.access-token-expiration-minutes=10
csrf.same-site=Lax
csrf.secure=true
csrf.http-only=false
app.security.trust-forwarded-headers=true
app.cors.allowed-origins[0]=https://l2terra.online
app.mail.frontend-verify-url=https://l2terra.online/verify-email
app.mail.frontend-reset-password-url=https://l2terra.online/reset-password
app.mail.frontend-two-factor-recovery-url=https://l2terra.online/recover-2fa
app.mail.frontend-game-accounts-url=https://l2terra.online/dashboard/game-accounts
app.mail.frontend-security-url=https://l2terra.online/dashboard-reset-password
app.mail.frontend-auth-url=https://l2terra.online/register
security.two-factor.recovery.request-cooldown-minutes=${SECURITY_TWO_FACTOR_RECOVERY_REQUEST_COOLDOWN_MINUTES:2}

logging.level.root=INFO
logging.level.com.terra.api=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
