spring.config.activate.on-profile=prod

# Production profile
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.cookie.same-site=Lax
jwt.cookie.http-only=true
jwt.cookie.secure=true
csrf.same-site=Lax
csrf.secure=true
csrf.http-only=false
app.security.trust-forwarded-headers=true
app.cors.allowed-origins[0]=https://l2terra.online
app.mail.frontend-verify-url=https://l2terra.online/verify-email
app.mail.frontend-reset-password-url=https://l2terra.online/reset-password

logging.level.root=INFO
logging.level.com.terra.api=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
