spring.config.activate.on-profile=dev

# Development profile
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.highlight_sql=false

jwt.secret=4d2a9f16b1c4e8870f52c93d7a6e14fb5c20a8d31e74f9b6c2d11a5e9f08bc47
jwt.access-token-expiration-minutes=1
jwt.cookie.same-site=Lax
jwt.cookie.http-only=true
jwt.cookie.secure=false
app.cors.allowed-origins[0]=http://localhost:4200
app.mail.frontend-verify-url=http://localhost:4200/verify-email
app.mail.frontend-reset-password-url=http://localhost:4200/reset-password

logging.level.root=INFO
logging.level.com.terra.api=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
